TOOLS_ROOT=../../../build/wasm

include $(TOOLS_ROOT)/common.mk
include $(TOOLS_ROOT)/wxwasm_gl.mk

TARGET=cube

SOURCES=cube_gles.cpp

EXTRA_INC_PATHS=-I.
CXXFLAGS=$(WX_CXXFLAGS)

LIBS=
LDFLAGS=-sTOTAL_MEMORY=64MB -sFULL_ES3=1 -sUSE_WEBGL2=1 -sWASM=1 $(WX_LDFLAGS)

JS=$(TOOLS_ROOT)/wx.js
HTML=$(TOOLS_ROOT)/template.html

$(eval $(call TARGET_RULE,$(TARGET),$(SOURCES),$(LIBS),$(LDFLAGS),$(JS),$(HTML)))
